e4_pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('trailers/', include('trailers.urls')),
    path('shows/', include('shows.urls')),
    path("subscription/", include('subscription.urls')),
    path("contributors/", include('contributors.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name="show_main"),
]

subscription/urls.py
from django.urls import path
from subscription.views import *

app_name = "subscription"

urlpatterns = [
    path("active-subscription/", get_active_subscription, name="get_active_subscription"),
    path("subscription-details/<str:package_name>/", get_subscription_details_by_name, name="get_subscription_details_by_name"),
    path("subscription-details/", get_all_subscription_details, name="get_all_subscription_details"),
    path("transactions/", get_transaction_history, name="get_transaction_history"),
    path("is-eligible-to-subscribe/", get_subscription_eligibilty, name="get_subscription_eligibilty"),
    path("purchase-subscription/", purchase_subscription, name="purchase_subscription"),
    path("", render_subscription_details, name="render_subscription_details"),
    path("subscribe/<str:package_name>/", render_subscription_purchase, name="render_subscription_purchase"),
]

subscription/views.py
from django.shortcuts import render, redirect
from utils.query import query
from django.http import JsonResponse
import datetime
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def get_active_subscription(request):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    username = request.session['username']

    if request.method == 'GET':
        active_subscription = query(
            """
            SELECT 
                t.nama_paket, 
                t.start_date_time, 
                t.end_date_time,
                t.metode_pembayaran,
                t.timestamp_pembayaran,
                p.harga, 
                p.resolusi_layar, 
                STRING_AGG(dp.dukungan_perangkat, ', ') AS dukungan_perangkat 
            FROM 
                transaction AS t 
            JOIN 
                paket AS p ON t.nama_paket = p.nama 
            JOIN 
                dukungan_perangkat AS dp ON p.nama = dp.nama_paket 
            WHERE 
                t.username = %s 
                AND (t.end_date_time IS NULL OR t.end_date_time > CURRENT_DATE) 
            GROUP BY 
                t.nama_paket, 
                t.start_date_time, 
                t.end_date_time, 
                p.harga, 
                p.resolusi_layar, 
                t.timestamp_pembayaran,
                t.metode_pembayaran
            ORDER BY 
                t.timestamp_pembayaran DESC 
            LIMIT 1;
            """,
            (username,)
        )

        message = ""
        if len(active_subscription) == 0:
            message = f"User {username} does not have any active subscription"
            context['active_subscription'] = None
        else:
            message = f"User {username} has active subscription"
            context['active_subscription'] = active_subscription[0]
        
        return JsonResponse({'status': 'success', 'data': context, 'message': message}, status=200)
    else:
        return JsonResponse({'status': 'error', 'message': 'Method not allowed'}, status=405)
    
def get_subscription_details_by_name(request, package_name):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    if request.method == "GET":
        package_details = query(
            """
            SELECT 
                p.nama, 
                p.harga, 
                p.resolusi_layar, 
                STRING_AGG(dp.dukungan_perangkat, ', ') AS dukungan_perangkat 
            FROM 
                paket AS p 
            JOIN 
                dukungan_perangkat AS dp ON p.nama = dp.nama_paket 
            WHERE 
                p.nama = %s 
            GROUP BY 
                p.nama, 
                p.harga, 
                p.resolusi_layar;
            """,
            (package_name,)
        )

        message = ""
        if len(package_details) == 0:
            message = f"Package {package_name} not found."
            context["package"] = None
        else:
            message = f"Package {package_name} found."
            context["package"] = package_details[0]

        return JsonResponse({"status": "success", "data": context, "message": message}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed."}, status=405)
    
def get_all_subscription_details(request):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    if request.method == "GET":
        all_packages = query(
            """
            SELECT 
                p.nama, 
                p.harga, 
                p.resolusi_layar, 
                STRING_AGG(dp.dukungan_perangkat, ', ') AS dukungan_perangkat 
            FROM 
                paket AS p 
            JOIN 
                dukungan_perangkat AS dp ON p.nama = dp.nama_paket 
            GROUP BY 
                p.nama, 
                p.harga, 
                p.resolusi_layar
            ORDER BY
                p.harga ASC;
            """
        )

        message = ""
        if len(all_packages) == 0:
            message = "No packages available."
            context["packages"] = None
        else:
            message = "Packages available."
            context["packages"] = all_packages

        return JsonResponse({"status": "success", "data": context, "message": message}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed."}, status=405)

def get_transaction_history(request):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    username = request.session["username"]

    if request.method == "GET":
        all_transaction = query(
            """
        SELECT DISTINCT
                t.nama_paket, 
                t.start_date_time, 
                t.end_date_time, 
                t.metode_pembayaran, 
                p.harga, 
                t.timestamp_pembayaran 
            FROM 
                transaction AS t 
            JOIN 
                paket AS p ON t.nama_paket = p.nama 
            JOIN 
                dukungan_perangkat AS dp ON p.nama = dp.nama_paket 
            WHERE 
                t.username = %s
            ORDER BY
                t.timestamp_pembayaran DESC;
            """, 
            (username,)
        )
        
        message = ""
        if len(all_transaction) == 0:
            message = f"User {username} doesn't have any transaction history."
            context["transactions"] = None
        else:
            message = f"Transaction history found for user {username}."
            context["transactions"] = all_transaction
        
        return JsonResponse({"status": "success", "data": context, "message": message}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed."}, status=405)

def is_eligible_to_subscribe(username):
    last_transaction = query(
        """
        SELECT MAX(start_date_time) 
        FROM transaction 
        WHERE username = %s
        """,
        (username,)
    )

    if last_transaction \
          and last_transaction[0]['max'] \
              and datetime.datetime.combine(last_transaction[0]['max'], datetime.datetime.min.time()) \
                > datetime.datetime.now() - datetime.timedelta(days=1):
        return False
    
    return True

def get_subscription_eligibilty(request):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    username = request.session['username']

    if request.method == "GET":
        eligibilty = is_eligible_to_subscribe(username)
        context['is_eligible'] = eligibilty
        if eligibilty == True:
            return JsonResponse({'status': 'success', 'data': context, 'message': 'You are eligible to subscribe.'}, status=200)
        else:
            return JsonResponse({'status': 'error', 'data': context, 'message': 'You are not eligible to subscribe. You already have an active subscription. Please wait for one day before purchasing.'}, status=403)
    else:
        return JsonResponse({'status': 'error', 'message': 'Method not allowed'}, status=405)

@csrf_exempt
def purchase_subscription(request):
    context = {}
    if 'username' not in request.session:
        return JsonResponse({'status': 'error', 'message': 'You are not logged in'}, status=403)
    
    username = request.session['username']

    if request.method == "POST":
        data = json.loads(request.body)
        package_name = data["package_name"]
        payment_method = data["payment_method"]

        if is_eligible_to_subscribe(username) == False:
            return JsonResponse({'status': 'error', 'message': 'You are not eligible to subscribe. You already have an active subscription. Please wait for one day before purchasing.'}, status=403)
        
        query(
            """
            INSERT INTO transaction (
                username, 
                nama_paket, 
                metode_pembayaran
            )
            VALUES 
                (%s, %s, %s);
            """,
            (
                username, 
                package_name, 
                payment_method
            )
        )

        return JsonResponse({'status': 'success', 'message': 'Subscription purchased successfully.'}, status=201)
    else:
        return JsonResponse({'status': 'error', 'message': 'Method not allowed'}, status=405)
    
def render_subscription_details(request):
    context = {
        "is_logged_in": False
    }

    if 'username' not in request.session:
        return redirect('authentication:login')
    else:
        context["is_logged_in"] = True
        context["username"] = request.session["username"]

    return render(request, "manage_subscription.html", context)

def render_subscription_purchase(request, package_name):
    context = {
        "is_logged_in": False
    }

    if 'username' not in request.session:
        return redirect('authentication:login')
    else:
        context["is_logged_in"] = True
        context["username"] = request.session["username"]
        context["package_name"] = package_name

    return render(request, "purchase_subscription.html", context)

subscription/templates/manage_subscription.html
{% extends 'base.html' %}

{% block content %}
<div class="mx-auto min-h-screen bg-[#242831] font-inter_tight pb-6">
    <div class="mb-12 text-slate-100 text-center">
        <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md">Manage your <span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">PacilFlix</span> subscription</h1>
        <p class="text-xl">The escape to the cinemas, on the palm of your hands.</p>
    </div>
    <div class="mt-10 mb-5 text-slate-100 text-center">
        <p class="text-xl">Your current active subscription package</p>
    </div>
    <div class="mx-auto px-8">
        <table class="text-sm text-left rtl:text-right text-white max-w-screen-lg mx-auto table-auto">
            <thead class="text-xs text-[#242831] uppercase bg-white">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Package type
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Price
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Screen resolution
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Supported device(s)
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Start date
                    </th>
                    <th scope="col" class="px-6 py-3">
                        End date
                    </th>
                </tr>
            </thead>
            <tbody id="subscriptionBody" class="bg-[#242831]">
            </tbody>
        </table>
    </div>
    <div class="mt-10 mb-5 text-slate-100 text-center">
        <p class="text-xl">Choose other subscription packages</p>
    </div>
    <div class="mx-auto px-8">
        {% comment %} Jika tidak eligible masukkan paragraph merah mengapa tidak eligible {% endcomment %}
        <p class="text-red-500 text-center pb-4" id="not-eligible-msg">
        </p>
        <table class="text-sm text-left rtl:text-right text-white max-w-screen-lg mx-auto table-auto">
            <thead class="text-xs text-[#242831] uppercase bg-white">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Package type
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Price
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Screen resolution
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Supported device(s)
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Purchase
                    </th>
                </tr>
            </thead>
            <tbody id="allSubscriptionPackagesBody" class="bg-[#242831]">
            </tbody>
        </table>
    </div>
    <div class="mt-10 mb-5 text-slate-100 text-center">
        <p class="text-xl">Your subscription transaction history</p>
    </div>
    <div class="mx-auto px-8 pb-8">
        <table class="w-full text-sm text-left rtl:text-right text-white mx-auto max-w-screen-lg table-auto">
            <thead class="text-xs text-[#242831] uppercase bg-white">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Package type
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Start date
                    </th>
                    <th scope="col" class="px-6 py-3">
                        End date
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Payment method
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Payment date
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Total expense
                    </th>
                </tr>
            </thead>
            <tbody id="allTransactionHistoryBody" class="bg-[#242831]">
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    async function fetchSubscriptionData() {
        return fetch("{% url 'subscription:get_active_subscription' %}").then((res) => res.json())
    }

    async function fetchAllSubscriptionPackages() {
        return fetch("{% url 'subscription:get_all_subscription_details' %}").then((res) => res.json())
    }

    async function fetchAllTransactionHistory() {
        return fetch("{% url 'subscription:get_transaction_history' %}").then((res) => res.json())
    }

    async function fetchSubscriptionEligibility() {
        return fetch("{% url 'subscription:get_subscription_eligibilty' %}").then((res) => res.json())
    }

    async function refreshSubscriptionData() {
        try {
            const data = await fetchSubscriptionData() ;

            if (data.status === 'success') {
                const subscription = data.data.active_subscription;
                const subscriptionBody = document.getElementById('subscriptionBody');

                if (subscription === null) {
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">-</th>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                    `;
                    subscriptionBody.innerHTML = '';
                    subscriptionBody.appendChild(row);
                } else {
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">${subscription.nama_paket}</th>
                        <td class="px-6 py-4">${subscription.harga}</td>
                        <td class="px-6 py-4">${subscription.resolusi_layar}</td>
                        <td class="px-6 py-4">${subscription.dukungan_perangkat}</td>
                        <td class="px-6 py-4">${subscription.start_date_time}</td>
                        <td class="px-6 py-4">${subscription.end_date_time}</td>
                    `;
                    subscriptionBody.innerHTML = '';
                    subscriptionBody.appendChild(row);
                }
            } else {
                console.error(data.message);
            }
        } catch (error) {
            console.error(error);
        }
    }

    async function refreshAllSubscriptionPackages() {
        try {
            const data = await fetchAllSubscriptionPackages();
            const subscriptionEligibility = await fetchSubscriptionEligibility();

            if (data.status === 'success') {
                const packages = data.data.packages;
                const allSubscriptionPackagesBody = document.getElementById('allSubscriptionPackagesBody');

                allSubscriptionPackagesBody.innerHTML = '';

                if (subscriptionEligibility.status === 'error' && subscriptionEligibility.data.is_eligible === false) {
                    const notEligibleMsg = document.getElementById('not-eligible-msg');
                    notEligibleMsg.style.display = 'block';
                    notEligibleMsg.innerHTML = subscriptionEligibility.message;
                }

                packages.forEach((package) => {
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">${package.nama}</th>
                        <td class="px-6 py-4">${package.harga}</td>
                        <td class="px-6 py-4">${package.resolusi_layar}</td>
                        <td class="px-6 py-4">${package.dukungan_perangkat}</td>
                        <td class="px-6 py-4">
                        <!-- Jika belum eligible, disable button -->
                        ${subscriptionEligibility.status === 'error' ? `
                            <button class="mt-5 w-full rounded-md font-bold text-gray-600 border border-gray-600 px-4 py-2 duration-200" disabled>
                                Purchase
                            </button>
                        ` : `
                            <button class="mt-5 w-full rounded-md font-bold border px-4 py-2 duration-200 text-white border-white hover:bg-white hover:text-[#242831]" 
                                onclick="redirectToSubscriptionPurchase('${package.nama}')">
                                Purchase
                            </button>`}
                        </td>
                    `;
                    allSubscriptionPackagesBody.appendChild(row);
                });
            } else {
                console.error(data.message);
            }
        } catch (error) {
            console.error(error);
        }
    }

    async function refreshAllTransactionHistory() {
        try {
            const data = await fetchAllTransactionHistory();

            if (data.status === 'success') {
                const transactionHistory = data.data.transactions;
                const allTransactionHistoryBody = document.getElementById('allTransactionHistoryBody');

                allTransactionHistoryBody.innerHTML = '';

                if (transactionHistory === null){
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">-</th>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                        <td class="px-6 py-4">-</td>
                    `;
                    allTransactionHistoryBody.innerHTML = '';
                    allTransactionHistoryBody.appendChild(row);
                } else {
                    transactionHistory.forEach((transaction) => {
                        const row = document.createElement('tr');
                        row.innerHTML = `
                            <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">${transaction.nama_paket}</th>
                            <td class="px-6 py-4">${transaction.start_date_time}</td>
                            <td class="px-6 py-4">${transaction.end_date_time}</td>
                            <td class="px-6 py-4">${transaction.metode_pembayaran}</td>
                            <td class="px-6 py-4">${transaction.timestamp_pembayaran}</td>
                            <td class="px-6 py-4">${transaction.harga}</td>
                        `;
                        allTransactionHistoryBody.appendChild(row);
                    });
                }
            } else {
                console.error(data.message);
            }
        } catch (error) {
            console.error(error);
        }
    }

    async function redirectToSubscriptionPurchase(packageName) {
        window.location.href = `/subscription/subscribe/${packageName}`
    }

    refreshSubscriptionData();
    refreshAllSubscriptionPackages();
    refreshAllTransactionHistory();
</script>
{% endblock script %}

subscription/templates/purchase_subscription.html
{% extends 'base.html' %}

{% block content %}
<div class="mx-auto min-h-screen bg-[#242831] font-inter_tight pb-6">
    <div class="mb-12 text-slate-100 text-center">
        <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md">Purchase <span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">PacilFlix</span> subscription</h1>
        <p class="text-xl">The escape to the cinemas, on the palm of your hands.</p>
    </div>
    <div class="mt-10 mb-5 text-slate-100 text-center">
        <p class="text-xl">To be purchased subscription package info</p>
    </div>
    <div class="mx-auto px-8">
        <table class="w-full text-sm text-left rtl:text-right text-white max-w-screen-lg mx-auto table-auto">
            <thead class="text-xs text-[#242831] uppercase bg-white">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Package type
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Price
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Screen resolution
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Supported device(s)
                    </th>
                </tr>
            </thead>
            <tbody id="subscriptionBody" class="bg-[#242831]">
                <tr id="package-row">
                </tr>
            </tbody>
        </table>
    </div>
    <div class="mx-auto px-8 pt-8 text-white">
        <form method="POST" onsubmit="purchaseSubscription(); return false;">
            {% csrf_token %}
            <p class="text-sm font-bold mb-2 text-center">Payment method</p>
            <div class="w-full max-w-lg mx-auto">
                <select onchange="validatePaymentMethodMsg()" id="id_payment_method" name="payment-method" class="block rounded-lg border border-gray-500 px-4 py-3 bg-[#333845] mx-auto">
                    <option value="" disabled selected>Select your payment method...</option>
                    <option value="Transfer Bank">Bank transfer</option>
                    <option value="Kartu Kredit">Credit card</option>
                    <option value="E-wallet">E-wallet</option>
                </select>
            </div>
            <p class="text-xs text-red-500 pt-2 text-center" id="not-eligible-msg"></p>
            <div class="pt-4 max-w-lg mx-auto">
                <button id="purchase-btn" type="submit" class="mt-5 w-full rounded-md font-bold text-gray-600 border border-gray-600 px-12 py-3 duration-200" disabled>PURCHASE</button>
            </div>
        </form>
    </div>
</div>

<script>
    const payment_field = document.getElementById('id_payment_method')

    async function fetchPackageDetails() {
        return fetch("{% url 'subscription:get_subscription_details_by_name' package_name %}").then((res) => res.json())
    }

    async function displayPackageDetails() {
        const data = await fetchPackageDetails();
        if (data.status === "success") {
            const packageDetails = data.data.package;
            if (packageDetails) {
                document.getElementById('package-row').innerHTML = `
                    <th scope="row" class="px-6 py-4 font-medium text-white whitespace-nowrap">${packageDetails.nama}</th>
                    <td class="px-6 py-4">${packageDetails.harga}</td>
                    <td class="px-6 py-4">${packageDetails.resolusi_layar}</td>
                    <td class="px-6 py-4">${packageDetails.dukungan_perangkat}</td>
                `;
            } else {
                document.getElementById('subscriptionBody').innerHTML = '<tr><td colspan="4" class="text-center py-4">Package not found.</td></tr>';
            }
        } else {
            document.getElementById('subscriptionBody').innerHTML = `<tr><td colspan="4" class="text-center py-4">${data.message}</td></tr>`;
        }
    }

    async function fetchSubscriptionEligibility() {
        return fetch("{% url 'subscription:get_subscription_eligibilty' %}").then((res) => res.json())
    }

    async function subscriptionEligibility() {
        const data = await fetchSubscriptionEligibility()
        const btn = document.getElementById("purchase-btn");

        if (data.status === "error" && data.data.is_eligible === false) {
            btn.classList.remove("text-white", "border-white", "hover:bg-white","hover:text-[#242831]")
            btn.disabled = true;
            document.getElementById('not-eligible-msg').innerText = data.message
            document.getElementById('id_payment_method').disabled = true
        }
    }

    const validatePaymentMethod = () => {
        return payment_field.value === ""
    }

    const validatePaymentMethodMsg = () => {
        const res = validatePaymentMethod()
        if (res) {
            payment_field.classList.add("border-red-500", "focus:outline-red-500");
        } else {
            payment_field.classList.remove("border-red-500", "focus:outline-red-500");
        }
        validateFields()
    }

    function validateFields() {
        const btn = document.getElementById("purchase-btn");
        if (
            !(
            validatePaymentMethod()
            )
        ) {
            btn.disabled = false;
            btn.classList.add("text-white", "border-white", "hover:bg-white","hover:text-[#242831]")
        } else {
            btn.classList.remove("text-white", "border-white", "hover:bg-white","hover:text-[#242831]")
            btn.disabled = true;
        }
    }

    async function getCurrentActiveSubscription() {
        return fetch("{% url 'subscription:get_active_subscription' %}").then((res) => res.json())
    }

    async function purchaseSubscription(event) {
        const data = await fetch("{% url 'subscription:purchase_subscription' %}", {
            method: "POST",
            body: JSON.stringify({
                package_name: "{{ package_name }}",
                payment_method: payment_field.value
            })
        }).then((res) => res.json())

        if (data.status === "success") {
            window.location.href = "{% url 'subscription:render_subscription_details' %}"
        } else {
            alert(data.message)
        }
    }

    validatePaymentMethodMsg()
    subscriptionEligibility()
    displayPackageDetails()
</script>
{% endblock content %}