e4_pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('trailers/', include('trailers.urls')),
    path('shows/', include('shows.urls')),
    path("subscription/", include('subscription.urls')),
    path("contributors/", include('contributors.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name="show_main"),
]

shows/urls.py
from django.urls import path
from shows import views
app_name = 'shows'

urlpatterns = [
    path("", views.show_tayangan, name="tayangan"),
    path('<str:id>/', views.tayangan_detail, name='detail'),
    path('<str:id>/episode/<str:sub_judul>/', views.episode_detail, name='episode'),
    path('save_review', views.save_review, name='save_review'),
    path('<str:id>/update_review/', views.update_review, name='update_review'),
    path('save_watching_history', views.save_watching_history, name='save_watching_history'),
]

shows/models.py
from django.db import models

# Create your models here.

shows/views.py
import datetime
import json
from django.http import JsonResponse
from django.shortcuts import redirect, render
from utils.query import query
from django.views.decorators.csrf import csrf_exempt
import psycopg2


def show_tayangan(request):
    context = {
        "is_logged_in": False
    }
    if 'username' not in request.session:
        return redirect('authentication:login')

    context["is_logged_in"] = True
    context["username"] = request.session["username"]

    tayangan = query("""
        SELECT 
            judul,
            sinopsis_trailer, 
            url_video_trailer, 
            to_char(release_date_trailer, 'DD-MM-YYYY') as release_date_trailer
        FROM
            TAYANGAN
        """)

    top_ten = query("""
        SELECT
            TAYANGAN.id,
            TAYANGAN.judul,
            TAYANGAN.sinopsis_trailer,
            TAYANGAN.url_video_trailer,
            to_char(TAYANGAN.release_date_trailer, 'DD-MM-YYYY') as release_date_trailer,
            COALESCE(total_view_all_time.total_view_all_time, 0) AS total_view_all_time,
            COALESCE(total_view_7_days.total_view_7_days, 0) AS total_view_7_days
        FROM
            TAYANGAN
        LEFT JOIN (
            SELECT
                t.id AS id_tayangan,
                SUM(e.durasi) AS total_duration
            FROM
                TAYANGAN t
            LEFT JOIN
                episode e ON t.id = e.id_series
            GROUP BY
                t.id
        ) AS series_total_duration ON TAYANGAN.id = series_total_duration.id_tayangan
        LEFT JOIN (
            SELECT
                t.id AS id_tayangan,
                f.durasi_film AS total_duration
            FROM
                TAYANGAN t
            LEFT JOIN
                film f ON t.id = f.id_tayangan
        ) AS film_total_duration ON TAYANGAN.id = film_total_duration.id_tayangan
        LEFT JOIN (
            SELECT
                COALESCE(std.id_tayangan, ftd.id_tayangan) AS id_tayangan,
                COALESCE(std.total_duration, ftd.total_duration) AS total_duration
            FROM
                (
                    SELECT
                        t.id AS id_tayangan,
                        SUM(e.durasi) AS total_duration
                    FROM
                        TAYANGAN t
                    LEFT JOIN
                        episode e ON t.id = e.id_series
                    GROUP BY
                        t.id
                ) AS std
            FULL OUTER JOIN (
                SELECT
                    t.id AS id_tayangan,
                    f.durasi_film AS total_duration
                FROM
                    TAYANGAN t
                LEFT JOIN
                    film f ON t.id = f.id_tayangan
            ) AS ftd ON std.id_tayangan = ftd.id_tayangan
        ) AS combined_total_duration ON TAYANGAN.id = combined_total_duration.id_tayangan
        LEFT JOIN (
            SELECT
                rn.id_tayangan,
                COUNT(*) AS total_view_7_days
            FROM
                riwayat_nonton rn
            JOIN (
                SELECT
                    COALESCE(std.id_tayangan, ftd.id_tayangan) AS id_tayangan,
                    COALESCE(std.total_duration, ftd.total_duration) AS total_duration
                FROM
                    (
                        SELECT
                            t.id AS id_tayangan,
                            SUM(e.durasi) AS total_duration
                        FROM
                            TAYANGAN t
                        LEFT JOIN
                            episode e ON t.id = e.id_series
                        GROUP BY
                            t.id
                    ) AS std
                FULL OUTER JOIN (
                    SELECT
                        t.id AS id_tayangan,
                        f.durasi_film AS total_duration
                    FROM
                        TAYANGAN t
                    LEFT JOIN
                        film f ON t.id = f.id_tayangan
                ) AS ftd ON std.id_tayangan = ftd.id_tayangan
            ) AS ctd ON rn.id_tayangan = ctd.id_tayangan
            WHERE
                end_date_time >= NOW() - INTERVAL '7 days'
                AND EXTRACT(EPOCH FROM (end_date_time - start_date_time))/60 >= 0.7 * ctd.total_duration
            GROUP BY
                rn.id_tayangan
        ) AS total_view_7_days ON TAYANGAN.id = total_view_7_days.id_tayangan
        LEFT JOIN (
            SELECT
                rn.id_tayangan,
                COUNT(*) AS total_view_all_time
            FROM
                riwayat_nonton rn
            JOIN (
                SELECT
                    COALESCE(std.id_tayangan, ftd.id_tayangan) AS id_tayangan,
                    COALESCE(std.total_duration, ftd.total_duration) AS total_duration
                FROM
                    (
                        SELECT
                            t.id AS id_tayangan,
                            SUM(e.durasi) AS total_duration
                        FROM
                            TAYANGAN t
                        LEFT JOIN
                            episode e ON t.id = e.id_series
                        GROUP BY
                            t.id
                    ) AS std
                FULL OUTER JOIN (
                    SELECT
                        t.id AS id_tayangan,
                        f.durasi_film AS total_duration
                    FROM
                        TAYANGAN t
                    LEFT JOIN
                        film f ON t.id = f.id_tayangan
                ) AS ftd ON std.id_tayangan = ftd.id_tayangan
            ) AS ctd ON rn.id_tayangan = ctd.id_tayangan
            WHERE
                EXTRACT(EPOCH FROM (end_date_time - start_date_time))/60 >= 0.7 * ctd.total_duration
            GROUP BY
                rn.id_tayangan
        ) AS total_view_all_time ON TAYANGAN.id = total_view_all_time.id_tayangan
        ORDER BY
            total_view_7_days DESC,
            total_view_all_time DESC,
            TAYANGAN.release_date_trailer DESC
        LIMIT 10;
    """)

    film = query("""
        SELECT 
            id,
            judul,
            sinopsis_trailer, 
            url_video_trailer, 
            to_char(release_date_trailer, 'DD-MM-YYYY') as release_date_trailer
        FROM 
            TAYANGAN
        JOIN 
            FILM f ON f.id_tayangan = TAYANGAN.id
        GROUP BY 
            TAYANGAN.id
        ORDER BY
            TAYANGAN.judul ASC;
        """)

    series = query("""
        SELECT
            id, 
            judul,
            sinopsis_trailer, 
            url_video_trailer, 
            to_char(release_date_trailer, 'DD-MM-YYYY') as release_date_trailer
        FROM 
            TAYANGAN
        JOIN 
            SERIES s ON s.id_tayangan = TAYANGAN.id
        GROUP BY 
            TAYANGAN.id
        ORDER BY
            TAYANGAN.judul ASC;
        """)

    pengguna = query("""
        SELECT
            username,
            to_char(end_date_time, 'DD-MM-YYYY') as end_date_time
        FROM
            TRANSACTION
        WHERE end_date_time > NOW()
        ORDER BY
            username ASC;
        """)

    context.update({'tayangan': tayangan, 'trailers': top_ten,
                   'film': film, 'series': series, 'pengguna': pengguna})
    return render(request, "shows.html", context)


def tayangan_detail(request, id):
    context = {
        "is_logged_in": False
    }
    if 'username' not in request.session:
        return redirect('authentication:login')

    context["is_logged_in"] = True
    context["username"] = request.session["username"]

    # Tayangan
    tayangan = query("""
        SELECT 
            t.id,
            t.judul,
            t.sinopsis, 
            t.asal_negara, 
            COALESCE(total_view_all_time.total_view_all_time, 0) AS total_view_all_time,
            STRING_AGG(DISTINCT gt.genre, ', ') AS genre,
            ROUND(COALESCE(AVG(u.rating),0), 1) AS rating_rata_rata
        FROM
            TAYANGAN AS t
        LEFT JOIN (
            SELECT 
                id_tayangan, 
                COUNT(*) AS total_view_all_time
            FROM 
                riwayat_nonton
            GROUP BY 
                id_tayangan
        ) AS total_view_all_time ON t.id = total_view_all_time.id_tayangan
        LEFT JOIN genre_tayangan AS gt ON t.id = gt.id_tayangan
        LEFT JOIN ULASAN AS u ON t.id = u.id_tayangan
        WHERE
            id = %s
        GROUP BY
            t.id,t.judul, t.sinopsis, t.asal_negara, total_view_all_time.total_view_all_time;
        """, (id,))

    # Film
    film = query("""
        SELECT
            durasi_film,
            release_date_film,
            url_video_film
        FROM 
            FILM
        LEFT JOIN tayangan t ON t.id = film.id_tayangan
        WHERE
            id_tayangan = %s;
        """, (id,))

    release_film = query("""
        SELECT
            id_tayangan, release_date_film
        FROM film
        WHERE
            release_date_film <= CURRENT_DATE;
        """)

    pemain = query("""
        SELECT
            nama
        FROM 
            CONTRIBUTORS
        LEFT JOIN memainkan_tayangan mt ON mt.id_pemain = CONTRIBUTORS.id
        LEFT JOIN tayangan t ON t.id = mt.id_tayangan
        WHERE
            t.id = %s
        GROUP BY
            nama;
        """, (id,))

    penulis = query("""
        SELECT
            nama
        FROM 
            CONTRIBUTORS
        LEFT JOIN menulis_skenario_tayangan ms ON ms.id_penulis_skenario = CONTRIBUTORS.id
        LEFT JOIN tayangan t ON t.id = ms.id_tayangan
        WHERE
            t.id = %s
        GROUP BY
            nama;
        """, (id,))

    sutradara = query("""
        SELECT
            nama
        FROM 
            CONTRIBUTORS
        LEFT JOIN sutradara s ON s.id = CONTRIBUTORS.id
        LEFT JOIN tayangan t ON t.id_sutradara = s.id
        WHERE
            t.id = %s

shows/templates/episode_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
    @media screen and (-webkit-min-device-pixel-ratio: 0) {
     
        input[type="range"]::-webkit-slider-thumb {
            width: 15px;
            -webkit-appearance: none;
  			appearance: none;
            height: 15px;
            cursor: ew-resize;
            background: #FFF;
            box-shadow: -405px 0 0 400px #605E5C;
            border-radius: 50%;
            
        }
    }
</style>
<div class="mx-auto min-h-screen bg-[#242831] font-inter_tight pb-6">
<div class="container mx-auto px-4 py-4" style="cursor: auto;">
    <div class="mb-12 text-slate-100 text-center">
        <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md"><span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">Episode</span> page</h1>
        <p class="text-xl">The escape to the cinemas, on the palm of your hands.</p>
    </div>
    <div class="flex flex-col">
        <div class="mb-4">
            <table>
                {% for eps in episode_khusus %}
                <tr>
                    <td class="text-left">
                        <div class="mt-10 mb-2 text-slate-100">
                            <p class="text-xl">Title: {{ eps.judul }}</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        <div class="mt-3 mb-2 text-slate-100">
                            <p class="text-xl">Episode title: {{ eps.sub_judul }}</p>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% for eps in release_episode %}
                    {% if episode_khusus.0.sub_judul == eps.sub_judul %}
                        <tr>
                            <td class="text-left">
                                <div class="mt-5">
                                    <input id="input-range-{{ eps.id_series }}" class="w-full rounded-lg overflow-hidden appearance-none bg-gray-400 h-4 w-128" type="range" min="1" max="100" step="1" value="0" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                <button type="submit" id="watch" onclick="saveWatchingHistory('{{ eps.id_series }}')" class="mt-5 w-full block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">Watch</button>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="text-left">
                        <div class="mt-3 mb-2 text-slate-100">
                            <p class="text-xl">Other episodes:</p>
                        </div>
                        <ul>
                            {% for eps in episode %}
                            <li class="mb-6 text-center">
                                <a href="{% url 'shows:episode' id=eps.id sub_judul=eps.sub_judul %}" class="mt-5 w-full block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">
                                    Episode {{ forloop.counter }}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="flex flex-col space-y-4">
        {% for eps in episode_khusus %}
        <div class="bg-[#333845] rounded-lg p-6 shadow-lg transition transform hover:-translate-y-1 hover:shadow-xl">
            <div class="text-white mb-4">
                <p class="text-2xl font-bold">Episode Synopsis</p>
                <p class="text-xl">{{ eps.sinopsis }}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Episode Duration: {{ eps.durasi }}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Episode URL: <a href="{{ eps.url_video }}" class="text-blue-400 hover:underline">{{ eps.url_video }}</a></p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Episode Release Date: {{ eps.release_date }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
</div>
<script>
    function saveWatchingHistory(id_tayangan) {
        const slider = document.getElementById(`input-range-${id_tayangan}`);
        const watchingPercentage = slider.value;

        console.log('watching_percentage:', watchingPercentage); // Debugging

        const data = {
            id_tayangan: id_tayangan,
            watching_percentage: watchingPercentage
        };

        fetch("{% url 'shows:save_watching_history' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data),
        })
        .then(response => {
            if (response.ok) {
                // Jika respons berhasil (status 201), perbarui halaman
                window.location.reload();
            } else {
                // Tangkap pesan kesalahan jika diperlukan
                return response.json().then(data => {
                    throw new Error(data.message);
                });
            }
        })
        .catch((error) => {
            alert('Error: ' + error.message);
        });
    }
</script>
{% endblock content %}

shows/templates/film_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
    @media screen and (-webkit-min-device-pixel-ratio: 0) {
     
        input[type="range"]::-webkit-slider-thumb {
            width: 15px;
            -webkit-appearance: none;
  			appearance: none;
            height: 15px;
            cursor: ew-resize;
            background: #FFF;
            box-shadow: -405px 0 0 400px #605E5C;
            border-radius: 50%;
            
        }
    }
</style>
<div class="mx-auto min-h-screen bg-[#242831] font-inter_tight pb-6">
<div class="container mx-auto px-4 py-4" style="cursor: auto;">
    <div class="mb-12 text-slate-100 text-center">
        <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md"><span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">Film</span> page</h1>
        <p class="text-xl">The escape to the cinemas, on the palm of your hands.</p>
    </div>
    <div class="flex flex-col">
        <div class="mb-4">
            <table>
                <tr>
                    <td class="text-left">
                        <div class="mt-10 mb-2 text-slate-100 text-left">
                            <p class="text-xl">Title: {{ tayangan.0.judul }}</p>
                        </div>
                    </td>
                </tr>
                {% for film in release_film %}
                    {% if tayangan.0.id == film.id_tayangan %}
                    <tr>
                        <td class="text-left">
                            <div class="mt-5">
                                <input id="input-range-{{ film.id_tayangan }}" class="w-full rounded-lg overflow-hidden appearance-none bg-gray-400 h-4 w-128" type="range" min="1" max="100" step="1" value="0" />
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td class="text-center">
                            <button type="submit" id="watch" onclick="saveWatchingHistory('{{ film.id_tayangan }}')" class="mt-5 w-full block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">Watch</button>
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <td class="text-center">
                        <a href="#" class="mt-5 w-full block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">
                            Download show
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="text-center">
                        <a href="#" class="mt-5 w-full block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">
                            Save to favourites
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="flex flex-col space-y-4">
        {% for t in tayangan %}
        <div class="bg-[#333845] rounded-lg p-6 shadow-lg transition transform hover:-translate-y-1 hover:shadow-xl">
            <div class="text-white mb-4">
                <p class="text-2xl font-bold">Total View: {{t.total_view_all_time}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Average Rating: {{t.rating_rata_rata}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Synopsis: {{t.sinopsis}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Genre: {{t.genre}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Country of Origin: {{t.asal_negara}}</p>
            </div>
        </div>
        {% endfor %}

        {% for f in film %}
        <div class="bg-[#333845] rounded-lg p-6 shadow-lg transition transform hover:-translate-y-1 hover:shadow-xl">
            <div class="text-white mb-4">
                <p class="text-xl">Film Duration: {{f.durasi_film}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Release Date: {{f.release_date_film}}</p>
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Film URL: <a href="{{ f.url_video_film }}" class="text-blue-400 hover:underline">{{ f.url_video_film }}</a></p>
            </div>
        </div>
        {% endfor %}

        <div class="bg-[#333845] rounded-lg p-6 shadow-lg transition transform hover:-translate-y-1 hover:shadow-xl">
            <div class="text-white mb-4">
                <p class="text-xl">Actors:</p>
                {% for actor in pemain %}
                <span class="block ml-5">- {{ actor.nama }}</span>
                {% endfor %}
            </div>
            <div class="text-white mb-4">
                <p class="text-xl">Screenwriters:</p>
                {% for actor in penulis %}
                <span class="block ml-5">- {{ actor.nama }}</span>
                {% endfor %}
            </div>
            <div class="text-white">
                <p class="text-xl">Director:</p>
                {% for actor in sutradara %}
                <span class="block ml-5">- {{ actor.nama }}</span>
                {% endfor %}
            </div>
        </div>
    </div>

    
    <div class="container mx-auto px-4 py-4">
        <div class="mb-12 text-slate-100 text-center">
            <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md"><span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">Review</span></h1>
        </div>
        <!-- Modal toggle -->
        <button data-modal-target="default-modal" data-modal-toggle="default-modal" class="mt-5 block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]" type="button">
            Give review
        </button>

        <!-- Main modal -->
        <div id="default-modal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 overflow-auto bg-gray-900 bg-opacity-50 flex justify-center items-center">
            <div class="bg-[#242831] rounded-lg overflow-hidden shadow-xl max-w-lg w-full">
                <!-- Modal content -->
                <div class="flex items-center justify-between p-4 border-b">
                    <h3 class="text-lg font-semibold text-white">Give your review</h3>
                    <button type="button" class="text-gray-400 hover:text-gray-500 focus:outline-none" data-modal-hide="default-modal">
                        <svg class="w-6 h-6" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M14.7 14.7c-.2.2-.5.2-.7 0L10 10.707 6.707 14c-.2.2-.5.2-.7 0-.2-.2-.2-.5 0-.7L9.293 10 6 6.707c-.2-.2-.2-.5 0-.7.2-.2.5-.2.7 0L10 9.293l3.293-3.293c.2-.2.5-.2.7 0 .2.2.2.5 0 .7L10.707 10l3.293 3.293c.2.2.2.5 0 .7z" fill="currentColor"/>
                        </svg>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-4">
                    <form method="post" id="post-form" action="{% url 'shows:save_review' %}">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="deskripsi" class="block text-white font-bold mb-2">Review description:</label>
                            <textarea name="deskripsi" id="deskripsi" class="w-full px-3 py-2 border rounded-lg"></textarea>
                        </div>
                        <div class="mb-4">
                            <label for="rating" class="block text-white font-bold mb-2">Rating:</label>
                            <input type="number" name="rating" id="rating" class="w-full px-3 py-2 border rounded-lg">
                        </div>
                        <div class="flex items-center justify-end p-4 border-t">
                            <button type="submit" id="submit" class="mt-5 block rounded-md font-bold border border-gray-600 px-12 py-3 duration-200 text-white border-white hover:bg-white hover:text-[#242831]">
                                Submit
                            </button>
                        </div>
                    </form>
                </div>
                <!-- Modal footer -->
            </div>
        </div>
    </div>
    
    <div id="error-container" style="color: red;"></div>



    <!-- Daftar ulasan -->
    <div class="container mx-auto px-4 py-4" id="review-container">
        
    </div>
</div>
</div>
<script>
    const modalToggleButtons = document.querySelectorAll('[data-modal-toggle]');
    const modalCloseButtons = document.querySelectorAll('[data-modal-hide]');
    const modal = document.getElementById('default-modal');

    // Function to toggle modal visibility
    function toggleModal() {
        modal.classList.toggle('hidden'); // Toggle visibility of the modal
    }

    // Add click event listener to each modal toggle button
    modalToggleButtons.forEach(button => {
        button.addEventListener('click', toggleModal);
    });

    // Add click event listener to each modal close button
    modalCloseButtons.forEach(button => {
        button.addEventListener('click', toggleModal);
    });

    function updateReview() {
        fetch("{% url 'shows:update_review' id=tayangan.0.id %}")
        .then(response => response.json())
        .then(data => {
            const reviewContainer = document.getElementById('review-container');
            reviewContainer.innerHTML = ''; // Clear previous content

            data.ulasan.forEach(review => {
                const card = document.createElement('div');
                card.classList.add('bg-[#333845]', 'rounded-lg', 'p-6', 'mb-4', 'shadow-lg', 'transition', 'transform', 'hover:-translate-y-1', 'hover:shadow-xl');

                card.innerHTML = `
                    <div class="text-white font-bold mb-2">
                        <span class="block text-xl">Username: ${review.username}</span>
                    </div>
                    <div class="text-white mb-2">
                        <span class="block">Deskripsi: ${review.deskripsi}</span>
                    </div>
                    <div class="text-white">
                        <span class="block">Rating: ${review.rating}</span>
                    </div>
                `;
                reviewContainer.appendChild(card);
            });
        })

        .catch(error => console.error('Error:', error));
    }

    function addReview(event) {
        event.preventDefault();
        const deskripsi = document.getElementById('deskripsi').value;
        const rating = document.getElementById('rating').value;
        const idTayangan = "{{ tayangan.0.id }}";
        
        // Send a POST request to save the new review
        fetch("{% url 'shows:save_review' %}", {
            method: "POST",
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': "{{ csrf_token }}"
            },
            body: JSON.stringify({
                id_tayangan: idTayangan,
                deskripsi: deskripsi,
                rating: rating
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === "success") {
                // Update the review container with the new data
                updateReview();
                // Reset form
                document.getElementById("post-form").reset();
                // Close modal
                toggleModal();
            } else {
                // If there is an error, display the error message
                updateReview();
                console.error('Error:', data.message);
                // You can display the error message in an alert or in an error container on your page
                // For example:
                const errorContainer = document.getElementById('error-container');
                errorContainer.innerText = data.message;
                document.getElementById("post-form").reset();
                toggleModal();
            }
        })
        .catch(error => console.error('Error:', error));
    }
    updateReview()

    function saveWatchingHistory(id_tayangan) {
        const slider = document.getElementById(`input-range-${id_tayangan}`);
        const watchingPercentage = slider.value;

        console.log('watching_percentage:', watchingPercentage); // Debugging

        const data = {
            id_tayangan: id_tayangan,
            watching_percentage: watchingPercentage
        };

        fetch("{% url 'shows:save_watching_history' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data),
        })
        .then(response => {
            if (response.ok) {
                // Jika respons berhasil (status 201), perbarui halaman
                window.location.reload();
            } else {
                // Tangkap pesan kesalahan jika diperlukan
                return response.json().then(data => {
                    throw new Error(data.message);
                });
            }
        })
        .catch((error) => {
            console.error('Error:', error);
        });
    }
    // Call the updateReview function when the page loads

    const postForm = document.getElementById('post-form');
    postForm.addEventListener('submit', addReview);
    
</script>

{% endblock content %}