contributors/urls.py
from django.urls import path
from contributors.views import *

app_name = "contributors"

urlpatterns = [
    path("", render_contributors, name="render_contributors"),
    path("writers/", get_writers, name="get_writers"),
    path("actors/", get_actors, name="get_actors"),
    path("directors/", get_directors, name="get_directors"),
]

e4_pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('trailers/', include('trailers.urls')),
    path('shows/', include('shows.urls')),
    path("subscription/", include('subscription.urls')),
    path("contributors/", include('contributors.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name="show_main"),
]

subscription/urls.py
from django.urls import path
from subscription.views import *

app_name = "subscription"

urlpatterns = [
    path("active-subscription/", get_active_subscription, name="get_active_subscription"),
    path("subscription-details/<str:package_name>/", get_subscription_details_by_name, name="get_subscription_details_by_name"),
    path("subscription-details/", get_all_subscription_details, name="get_all_subscription_details"),
    path("transactions/", get_transaction_history, name="get_transaction_history"),
    path("is-eligible-to-subscribe/", get_subscription_eligibilty, name="get_subscription_eligibilty"),
    path("purchase-subscription/", purchase_subscription, name="purchase_subscription"),
    path("", render_subscription_details, name="render_subscription_details"),
    path("subscribe/<str:package_name>/", render_subscription_purchase, name="render_subscription_purchase"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "head.html" %}
    {% block meta %}
    {% endblock meta %}
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
</body>
{% block script %}
{% endblock script %}
</html>

templates/head.html
{% load static %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="The escape to the cinemas, on the palm of your hands. | Made for TK BasDat by E4">
<title>E4 - Pacilflix</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&family=Inter:wght@100..900&display=swap" rel="stylesheet">
<style type="text/tailwindcss">
    @layer utilities {
        .nav-btn:hover:after{
            width:100%
        }
    }
</style>
<script>
    tailwind.config = {
        theme: {
            extend: {
                fontFamily: {
                    inter_tight: ["Inter Tight", "sans-serif"],
                    inter: ["Inter", "sans-serif"],
                }
            }
        }
    }
</script>

templates/navbar.html
<nav class="{% if is_authenticated %}sticky top-0 z-10{% endif %} bg-[#333845] font-inter_tight">
    <div class="flex items-center justify-between px-8">
        <div class="flex items-center">
            <div class="py-6 mr-4">
                {% if not is_logged_in %}
                <a href="/" class="inline font-bold text-2xl text-white"><span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">PacilFlix</span> - E4</a>
                {% endif %}
                {% if is_logged_in %}
                <a href="/shows/" class="inline font-bold text-2xl text-white"><span class="bg-gradient-to-r from-blue-500 to-red-500 text-transparent bg-clip-text">PacilFlix</span> - E4</a>
                {% endif %}
            </div>
            <div class="flex font-semibold items-center text-white gap-12 pl-14">
                {% if not is_logged_in %}
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="/trailers">Trailers</a>
                {% endif %}
                {% if is_logged_in %}
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="/shows/">Shows</a>
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="{% url 'contributors:render_contributors' %}">Contributors</a>
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="#">Favorites</a>
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="#">Downloads</a>
                <a class="nav-btn relative after:content-[''] after:bg-white after:h-[2px] after:w-[0%] after:left-0 after:-bottom-[5px] after:rounded-xl after:absolute after:duration-300" href="{% url 'subscription:render_subscription_details' %}">Subscription</a>
                {% endif %}
            </div>
        </div>
        {% if is_logged_in %}
        <div class="flex">
            <p class="font-medium text-white">{{username}}</p>
            <a href="/auth/logout" class="text-white hover:text-red-500 duration-100 pl-6">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <title id="title">Logout</title>
                    <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
                </svg>                  
            </a>
        </div>
        {% endif %}
    </div>
</nav>